articles/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.index, name='home'),
    path('article/', views.PostList.as_view(), name='articles'),
    path('<slug:slug>/', views.PostDetail.as_view(), name='post_detail'),
    path('like/<slug:slug>', views.PostLike.as_view(), name='post_like'),
    path('profile', views.profile, name='profile'),
    path('publish', views.publish, name='publish'),
    path('my_articles', views.my_articles, name='my_articles'),
    path('edit/<post_id>', views.edit_article, name='edit'),
    path('delete/<post_id>', views.delete_post, name='delete'),
]

booking/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.booking, name='booking'),
    path(
        'delete/<int:booking_id>', views.delete_booking, name="delete-booking"
        ),
    path('edit/<int:booking_id>', views.edit_booking, name='edit-booking'),
]

runningclub/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('website.urls'), name='website_urls'),
    path('articles/', include('articles.urls'), name='articles_urls'),
    path('accounts/', include('allauth.urls')),
    path('booking/', include('booking.urls')),
]

articles/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField

STATUS = ((0, "Draft"), (1, "Published"))


class Post(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="article_posts")
    updated_on = models.DateTimeField(auto_now=True)
    content = models.TextField()
    featured_image = CloudinaryField('image', default='placeholder')
    excerpt = models.TextField(blank=True)
    created_on = models.DateField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)
    likes = models.ManyToManyField(
        User, related_name='articles_likes', blank=True)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title
        
    def number_of_likes(self):
        return self.likes.count()


class Comment(models.Model):
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name="comments")
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created_on = models.DateField(auto_now=True)
    approved = models.BooleanField('Approved', default=False)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return f"Comment {self.body} by {self.name}"

booking/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField
from django import forms


# Create model for booking a running session

class Booking(models.Model):
    BEGINNERS = 'B'
    INTERMEDIATE = 'I'
    ADVANCED = 'A'
    SESSIONS_CHOICES_CHOICES = [
        (BEGINNERS, 'Running group for beginners level'),
        (INTERMEDIATE, 'Running group for intermediate level'),
        (ADVANCED, 'Running group for advanced runners'),
    ]
    sessions_type = models.CharField(
        max_length=1,
        choices=SESSIONS_CHOICES_CHOICES,
        default=BEGINNERS,
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE)

    booking_date_time = models.DateTimeField(auto_now=False, blank=True)

    confirmed = models.BooleanField(default=False)


class Home(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)


class Booking_detail(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)

articles/forms.py
from .models import Comment, Post
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'content', 'excerpt', 'featured_image',)


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

booking/forms.py
from .models import Booking
from django import forms
from django.forms import ModelForm
from django.contrib.admin import widgets


class BookingForm(ModelForm):
    booking_date_time = forms.DateTimeField(
        input_formats=['%d/%m/%Y %H:%M'],
    )

    class Meta:
        model = Booking
        exclude = ["confirmed", "user"]

articles/views.py
from django.shortcuts import render, get_object_or_404, reverse, redirect
from django.views import generic, View
from django.http import HttpResponseRedirect
from .models import Post
from .forms import CommentForm, ArticleForm, UserRegisterForm
from django.contrib.auth.models import User
from django.utils.text import slugify
from django.contrib import messages


def index(request):

    return render(request, "index.html")


class PostList(generic.ListView):
    model = Post
    queryset = Post.objects.filter(status=1).order_by("-created_on")
    template_name = "article.html"
    paginate_by = 6


def profile(request):

    return render(request, "profile.html")


def publish(request):

    if request.method == 'POST':
        article_form = ArticleForm(request.POST, request.FILES)

        if article_form.is_valid():
            form = article_form.save(commit=False)
            form.author = User.objects.get(username=request.user.username)
            form.slug = form.title.replace(" ", "-")
            messages.success(
                request, 'Your article post has been submitted for approval')
            form.save()
      
        return redirect('my_articles')

    article_form = ArticleForm()
    context = {'article_form': article_form}

    return render(request, 'publish.html', context)


def my_articles(request):

    logged_in_user = request.user
    logged_in_user_posts = Post.objects.filter(author=logged_in_user)
    return render(request, 'my_articles.html', {'posts': logged_in_user_posts})


def edit_article(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.method == 'POST':
        article_form = ArticleForm(request.POST, instance=post)
        if article_form.is_valid():
            form = article_form.save(commit=False)
            form.approved = False
            messages.success(
                request, 'Updated article post has been submitted for approval'
            )
            form.save()

            return redirect('my_articles')
    article_form = ArticleForm(instance=post)
    context = {'article_form': article_form}

    return render(request, 'edit_article.html', context)


def delete_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    post.delete()
    messages.success(request, 'Article deleted!')

    return redirect('my_articles')


class PostDetail(View):

    def get(self, request, slug, *args, **kwargs):
        queryset = Post.objects.filter(status=1)
        post = get_object_or_404(queryset, slug=slug)
        comments = post.comments.filter(approved=True).order_by("-created_on")
        liked = False
        if post.likes.filter(id=self.request.user.id).exists():
            liked = True

        return render(
            request,
            "post_detail.html",
            {
                "post": post,
                "comments": comments,
                "commented": False,
                "liked": liked,
                "comment_form": CommentForm()
            },
        )

    def post(self, request, slug, *args, **kwargs):
        queryset = Post.objects.filter(status=1)
        post = get_object_or_404(queryset, slug=slug)
        comments = post.comments.filter(approved=True).order_by("-created_on")
        liked = False
        if post.likes.filter(id=self.request.user.id).exists():
            liked = True

        comment_form = CommentForm(data=request.POST)

        if comment_form.is_valid():
            comment_form.instance.email = request.user.email
            comment_form.instance.name = request.user.username
            comment = comment_form.save(commit=False)
            comment.post = post
            comment.save()
        else:
            comment_form = CommentForm()

        return render(
            request,
            "post_detail.html",
            {
                "post": post,
                "comments": comments,
                "commented": True,
                "liked": liked,
                "comment_form": CommentForm()
            },
        )


class PostLike(View):

    def post(self, request, slug):
        post = get_object_or_404(Post, slug=slug)

        if post.likes.filter(id=request.user.id).exists():
            post.likes.remove(request.user)
        else:
            post.likes.add(request.user)

        return HttpResponseRedirect(reverse('post_detail', args=[slug]))


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f"Account created for {username}!")

            return redirect('profile')
   
        else:
            form = UserRegisterForm()
        return render(request, 'account/signup.html', {'form': form})

booking/views.py
from django.shortcuts import render, HttpResponse, get_object_or_404, reverse, redirect
from django.views import generic, View
from django.http import HttpResponse
from .forms import BookingForm
from booking.models import (Booking, Home, Booking_detail)
import calendar
from calendar import HTMLCalendar
from datetime import datetime
from django.contrib.auth.decorators import login_required
from django.contrib import messages


@login_required
def booking(request):
    if request.method == "GET":
        booking_form = BookingForm()
        existing_bookings = Booking.objects.filter(
            confirmed=True, user=request.user
        )
        return render(request, 'booking.html', context={
            "form": booking_form, "existing_bookings": existing_bookings})

    elif request.method == "POST":
        booking_form = BookingForm(request.POST)
        if booking_form.is_valid():
            reservation = booking_form.save(commit=False)
            reservation.user = request.user
            reservation.save()
            messages.add_message(
                request, messages.SUCCESS, 'Booking successful.')
            return render(request, 'booking_detail.html', {
                "booking": reservation})
        else:
            return render(request, 'booking.html', {"form": booking_form})


@login_required
def bookings(request):
    pass


@login_required
def edit_booking(request, booking_id):
    existing_booking = get_object_or_404(Booking, pk=booking_id)
    if existing_booking.user != request.user:
        messages.error(request, 'this is not your booking')
        return redirect("index")

    if request.method == "POST":
        booking_form = BookingForm(request.POST, instance=existing_booking)
        if booking_form.is_valid():
            print(booking_form.cleaned_data)
            booking_form.save()
            messages.success(request, 'Booking updated successfully.')
            return redirect('booking')
        else:
            return redirect('booking')

    print(existing_booking)
    booking_form = BookingForm(instance=existing_booking)

    return render(request, 'booking.html', context={"form": booking_form})


@login_required
def delete_booking(request, booking_id):
    existing_bookings = get_object_or_404(Booking, pk=booking_id)
    if existing_bookings.user != request.user:
        messages.error(request, 'this is not your booking')
        return redirect("index")
    existing_bookings.delete()

    return redirect('booking')


def homepage(request):
    return render(request, "index.html")

templates/article.html
{% extends "base.html" %}

{% block content %}

<div class="container-fluid">
    <div class="row">

        <!-- Blog Entries Column -->
        <div class="col-12 mt-3 left">
            <div class="row">
                {% for post in post_list %}
                <div class="col-md-4">
                    <div class="card mb-4">
                        <div class="card-body">
                            <div class="image-container">
                                {% if "placeholder" in post.featured_image.url %}
                                <img class="card-img-top"
                                    src="https://res.cloudinary.com/deqj8dkeq/image/upload/v1666455625/Portfolio%204/madvjqs911bypjpha20b.webp" alt="Man running">
                                {% else %}
                                <img class="card-img-top" src=" {{ post.featured_image.url }}">
                                {% endif %}
                                <div class="image-flash">
                                    <p class="author">Author: {{ post.author }}</p>
                                </div>
                            </div>
                            <a href="{% url 'post_detail' post.slug %}" class="post-link">
                                <h2 class="card-title">{{ post.title }}</h2>
                                <p class="card-text">{{ post.excerpt }}</p>
                            </a>
                            <hr>
                            <p class="card-text text-muted h6">{{ post.created_on}} <i class="far fa-heart"></i>
                                {{ post.number_of_likes }}</p>
                        </div>
                    </div>
                </div>
                {% if forloop.counter|divisibleby:3 %}
            </div>
            <div class="row">
                {% endif %}
                {% endfor %}

            </div>
        </div>
    </div>
    {% if is_paginated %}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
            {% endif %}
            {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>

            {% endif %}
        </ul>
    </nav>
    {% endif %}
</div>
{%endblock%}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html class="h-100" lang="en">

<head>
    <title>The Running Club</title>

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous">
    </script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="icon" type="image/png" href="https://res.cloudinary.com/deqj8dkeq/image/upload/v1667125133/Portfolio%204/favicon_rtyy9v.png">

</head>

<body class="d-flex flex-column h-100 main-bg">

    <!-- Navigation -->

    <nav class="navbar navbar-expand-lg navbar-light bg-white header-bar">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'index' %}"><span class="brand">The Running Club</span></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
                aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'articles' %}">Articles</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'booking' %}">Book</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'profile' %}">Account</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_signup' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_login' %}">Login</a>
                    </li>
                    {% endif %}
                </ul>
                <span class="navbar-text text-muted">
                    Eat, Sleep and Run!
                </span>
            </div>
        </div>
    </nav>

    <div class="container">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible fade show" id="msg" role="alert">
                    {{ message | safe }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <main class="flex-shrink-0 main-bg">
        {% block content %}
        <!-- Content Goes here -->
        {% endblock content %}
    </main>

    <!-- Footer -->
    <footer class="footer mt-auto py-3 dark-bg">
        <p class="m-0 text-center text-white">Made by Steven Smith 2022</p>
        <p class="m-0 text-center text-white">Follow us: 
            <a href="https://www.facebook.com"><i class="fab fa-facebook-square ms-3"></i></a>
            <a href="https://www.twitter.com"><i class="fab fa-twitter-square ms-3"></i></a>
            <a href="https://www.instagram.com"><i class="fab fa-instagram-square ms-3"></i></a>
            <a href="https://www.youtube.com"><i class="fab fa-youtube-square ms-3"></i></a>
        </p>
    </footer>
    <script>
        setTimeout(function() {
            let messages = document.getElementById("msg");
            let alert = new bootstrap.Alert(messages);
            alert.close();
        }, 3000);
    </script>
</body>

</html>

templates/booking.html
{% extends 'base.html' %}

{% block content %}

{% load crispy_forms_tags %}
<h1 class="px-3">Welcome to the Running Club Booking page</h1>

<div class="px-3">
  <p>To book your run complete the form below:</p>
  <p>When entering a date/time please type in the following format: dd/mm/yy 00:00.</p>
</div>

<div class="container-fluid post-from-container w-25 ">
  <form action = "" method="POST">
    {% csrf_token %}
    {{ form|crispy }}
        
        <script>
          $(function () {
            $("#id_booking_date_time").datetimepicker({
              format: 'd/m/Y H:i',
            });
          });
        </script>

    <button class="btn btn-signup btn-lg" type="submit" value="submit">Submit
    </button>
  </form>
</div>

<h5 class="px-3">Your scheduled runs:</h5>
{% for booking in existing_bookings %}
<div class="px-3">
<div>{{booking.session_type}}
</div>
<div>{{booking.booking_date_time}}
</div>
  <button onclick="return confirm('Are you sure you want to reschedule your run?')">
    <a class="btn btn-warning" href="{% url 'edit-booking' booking.id %}">Reschedule
    </a>
  </button>
  <button onclick="return confirm('Are you sure you want to cancel your run?')">
    <a class="btn btn-danger" href="{% url 'delete-booking' booking.id %}">Cancel
    </a>
  </button>
</div>

{% endfor %}

{% endblock %}

templates/booking_detail.html
{% extends 'base.html' %} 
{% block content %}
{% load crispy_forms_tags %}
<h1>Your Run
</h1>
<p> Thank you. Your booking details have been submitted 
</p>
<div>Session Type: {{ booking.session_type }}
</div>
<div>Booking time: {{ booking.booking_date_time }}
</div>
{% if booking.confirmed %}
<span>Booking confirmed
</span>
{% else %}
<span>Booking not confirmed yet
</span>
{% endif %}
<button class="join-button" type="submit" value="submit">
  <a class="btn btn-warning" href="{% url 'booking' %}">Reschedule
  </a>
</button>
<button onclick="return confirm('Are you sure you want to cancel your run?')" class="join-button" type="submit" value="submit">
  <a class="btn btn-danger" href="{% url 'index' %}">Cancel booking
  </a>
</button>
{%endblock%}

templates/edit_article.html
{% extends "base.html" %}

{% block content %}

{% load crispy_forms_tags %}

<div class="container-fluid post-form-container">

    {% if user.is_authenticated %}
    <h3 class="title">Edit Article</h3>
    <p>Editing as: {{ user.username }}</p>
    <form method="POST">
        {{ article_form | crispy }}
        {% csrf_token %}
        <button type="submit" class="btn btn-signup btn-lg">Update Article</button>
        {% if updated %}
        {{ message }}
    </form>
    {% endif %}
    {% endif %}
    
</div>

{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block content %}

<header class="bg-light container">
    <div class="page-header min-vh-75 bg-gradient-dark" style="height: 500px; background-image:
    url('https://res.cloudinary.com/deqj8dkeq/image/upload/v1667039306/front_page_remylw.jpg')">
      <div class="container">
			  <div class="row">
				  <div class="col-lg-8 col-md-10 mx-auto">
					</div>
				</div>
			</div>
		</div>
</header>

<div class="container">
  <h2 class="home-title">Welcome to The Running Club</h2>
  <p>
    The Running Club is a place for everything running. From guidance and techniques to improve your running, to what 
    the best running shoes to wear are.  Running is a forever changing sport and there are a lot of good ideas outhere!
    So if you are new to running and are looking for top tips or even if your a seasoned runner who wants to share your
    experience, then this is place for you!
</p>
</div>

<div class="container-fluid">
  <div class="row intro-msg">
    <p>Talk everything about running!</p>
    <p>Read articles from across the globe in giving you advice and guidance to improve your running</p>
    <p>If you have any top tips or topics, then please share with the community!</p>
  </div>
  <div class="d-flex justify-content-center">
    {% if user.is_authenticated %}
      <a class="btn btn-signup btn-lg btn-link" href="{% url 'profile' %}">ACCOUNT</a>
    {% else %}
      <a class="btn btn-signup btn-lg btn-link" href="{% url 'account_login' %}">LOGIN</a>
    {% endif %}

  </div>
</div>
<div>
  <p></p>
</div>
{% endblock %}

templates/my_articles.html
{% extends "base.html" %}

{% block content %}

<div class="container-fluid my-articles-container mx-auto">
    <h3 class="title">My Articles:</h3>

    {% for post in posts %}
        <div class="card my-list">
            <h5 class="card-header">
                <a href="{% url 'post_detail' post.slug %}" class="published">{{ post.title }}</a>
            </h5>        
            <div class="card-body my-list-box">
                {% if post. %}
                <h5 class="card-title">
                </h5>
                {% endif %}
                <p class="card-text">{{ post.excerpt }}</p>
                <p class="card-text my-article-date">{{ post.created_on }}</p>
                <a class="btn btn-danger btn-lg" href="edit/{{ post.id }}">Edit</a>
                <button class="btn btn-danger btn-lg" data-bs-toggle="modal" data-bs-target="#deleteModal{{ post.id }}">Delete</button>
            </div>
        </div>

        <!--Modal-->

        <div class="modal fade" id="deleteModal{{ post.id }}" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content delete-modal">
                    <div class="modal-header">
                        <h5 class="modal-title" id="deleteModalLabel">Delete</h5>
                        <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true"><i class="fas fa-times"></i></span>
                        </button>
                    </div>
                    <div class="modal-body">
                        Are you sure you want to delete "{{ post.title }}"?
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                        <a class="btn btn-danger" href="delete/{{ post.id }}">Delete</a>
                    </div>
                </div>
            </div>
        </div>

        {% empty %}
        <p>You have no articles</p>
        <a class="btn btn-signup btn-lg profile-item-link" href="{% url 'publish' %}">Publish an Article</a>
    {% endfor %}
    
</div>

{% endblock %}

templates/post_detail.html
{% extends 'base.html' %} {% block content %}

{% load crispy_forms_tags %}

<div class="masthead">
    <div class="container">
        <div class="row g-0">
            <div class="col-md-6 masthead-text">
                <!-- Post title goes in these h1 tags -->
                <h1 class="post-title">{{ post.title }}</h1>
                <!-- Post author goes before the | the post's created date goes after -->
                <p class="post-subtitle">{{ post.author }} | {{ post.created_on }}</p>
            </div>
            <div class="d-none d-md-block col-md-6 masthead-image">
                <!-- The featured image URL goes in the src attribute -->
                {% if "placeholder" in post.featured_image.url %}
                <img src="https://res.cloudinary.com/deqj8dkeq/image/upload/v1666810883/Portfolio%204/Man-running-beach_n45mai.jpg" alt="Man Running on Beach">
                {% else %}
                <img src=" {{ post.featured_image.url }}" width="100%">
                {% endif %}
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col card mb-4  mt-3 left  top">
            <div class="card-body">
                <!-- The post content goes inside the card-text. -->
                <!-- Use the | safe filter inside the template tags -->
                <p class="card-text ">
                    {{ post.content | safe }}
                </p>
                <div class="row">
                    <div class="col-1">
                        <strong>
                            {% if user.is_authenticated %}
                            <form class="d-inline" action="{% url 'post_like' post.slug %}" method="POST">
                                {% csrf_token %}
                                {% if liked %}
                                <button type="submit" name="blogpost_id" value="{{post.slug}}" class="btn-like"><i class="fas fa-heart"></i></button>
                                {% else %}
                                <button type="submit" name="blogpost_id" value="{{post.slug}}" class="btn-like"><i class="far fa-heart"></i></button>
                                {% endif %}
                            </form>
                            {% else %}
                            <span class="text-secondary"><i class="far fa-heart"></i></span>
                            {% endif %}
                        <!-- The number of likes goes before the closing strong tag -->
                        <span class="text-secondary">{{ post.number_of_likes }} </span>
                        </strong>
                    </div>
                    <div class="col-1">
                        {% with comments.count as total_comments %}
                        <strong class="text-secondary"><i class="far fa-comments"></i>
                            <!-- Our total_comments variable goes before the closing strong tag -->
                            {{ total_comments }}</strong>
                        {% endwith %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <hr>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 card mb-4  mt-3 ">
            <h3>Comments:</h3>
            <div class="card-body">
                <!-- We want a for loop inside the empty control tags to iterate through each comment in comments -->
                {% for comment in comments %}
                <div class="comments" style="padding: 10px;">
                    <p class="font-weight-bold">
                        <!-- The commenter's name goes here. Check the model if you're not sure what that is -->
                        {{ comment.name }}
                        <span class=" text-muted font-weight-normal">
                            <!-- The comment's created date goes here -->
                            {{ comment.created_on }}
                        </span> wrote:
                    </p>
                    <!-- The body of the comment goes before the | -->
                    {{ comment.body | linebreaks }}
                </div>
                <!-- Our for loop ends here -->
                {% endfor %}
            </div>
        </div>
        <div class="col-md-4 card mb-4  mt-3 ">
            <div class="card-body">
                {% if commented %}
                <div class="alert alert-success" role="alert">
                    Your comment is awating approval
                </div>
                {% else %}

                {% if user.is_authenticated %}

                <h3>Leave a comment:</h3>
                <p>Posting as: {{ user.name }}</p>
                <form method="post" style="margin-top: 1.3em">
                    {{ comment_form | crispy }}
                    {% csrf_token %}
                    <button type="submit" class="btn btn-signup btn-lg">Submit</button>
                </form>

                {% endif %}
                {% endif %}

            </div>
        </div>
    </div>
</div>

{% endblock content %}